# Generated by Django 5.1.7 on 2025-12-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diner_hashed_password_staff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='someone@example.com', max_length=200)),
                ('hashed_password', models.CharField(default='some_hash', max_length=128)),
                ('phone_num', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('DINER', 'Diner'), ('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('WAITER', 'Waiter')], max_length=20)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
