# Generated by Django 5.1.7 on 2025-12-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004a_migrate_staff_diner_to_user'),
        ('orders', '0005_alter_order_diner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diner',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
