# Generated by Django 5.1.7 on 2025-12-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004a_migrate_staff_diner_to_user'),
        ('orders', '0004_alter_payment_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='diner',
            field=models.ForeignKey(limit_choices_to={'role': 'DINER'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
