# Generated by Django 5.1.7 on 2025-12-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user'),
        ('reviews', '0003_alter_feedback_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='diner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DINER'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
